services:

  db: 
    image: ankane/pgvector
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
    ports: 
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/data
      OLLAMA_HOST: http://ollama:11434
    depends_on:
      - db
      - ollama_init
    
  frontend:
    build: ./frontend
    ports: 
      - '8501:8501'
    depends_on:
      - backend

  ollama:
    image: ollama/ollama
    ports: 
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama

  ollama_init:
    image: ollama/ollama
    depends_on:
      - ollama
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: >
      /bin/sh -c "
        until ollama list >/dev/null 2>&1; do
          echo 'waiting for ollama...';
          sleep 2;
        done;
        ollama pull llama3
      "

volumes:
  pgdata:
  ollama_data: